### ISSUE TITLE
Colorize match results based on winner

### ISSUE THREAD

**Issue by Sephyros** [Sephyros/fwc2022calendar#2]
Just as preview image shows...

**Comment by JacoBSmitH101** [comment]
Would like to work on this.

**Comment by Sephyros** [comment]
> Would like to work on this.

Go for it! The idea of this calendar is to be as simple as possible, using only html, css and js (pure). Much of what we do can be done faster with frameworks, libraries/packages, etc, but the idea here is not to be fast, but to bring understanding and concepts of the fundamentals.

**Comment by Sephyros** [comment]
@JacoBSmitH101 
> Would like to work on this.

Go for it! The idea of this calendar is to be as simple as possible, using only html, css and js (pure). Much of what we do can be done faster with frameworks, libraries/packages, etc, but the idea here is not to be fast, but to bring understanding and concepts of the fundamentals.

**Comment by JacoBSmitH101** [comment]
Nice to hear, I've just been looking around for small repos to help out on and this was a perfect place for my first pull. Ill have a look at some of the other issues to see if theres anything that I can do.

**Comment by Sephyros** [comment]
Closed by Commit 3895bc1 and 05870a0

**Comment by Sephyros** [comment]
Closed by Commit 3895bc141d7aa81f3e99f7b5cd28620f2996579c and 05870a03669b241162ce317b57f1577c7256e75e
